export type Brother = {
  id: string;
  name: string;
  major: string;
  pcClass: string;
  role?: string;
  internship?: string;
  hometown: string;
  linkedin?: string;
};

// Active chapter roster imported from the latest member list.
export const brothers: Brother[] = [
  { id: "derek-bahl", name: "Derek Bahl", major: "Finance", pcClass: "Alpha", hometown: "Rye, NY", linkedin: "https://www.linkedin.com/in/Bahl.36" },
  { id: "connor-benke", name: "Connor Benke", major: "Finance", pcClass: "Alpha", hometown: "Tuckahoe, NY", linkedin: "https://www.linkedin.com/in/Benke.6" },
  { id: "anvi-bhavanam", name: "Anvi Bhavanam", major: "Finance", pcClass: "Alpha", hometown: "Dallas, Texas", linkedin: "https://www.linkedin.com/in/Bhavanam.3" },
  { id: "hayes-bubnick", name: "Hayes Bubnick", major: "Finance", pcClass: "Alpha", hometown: "Medina, OH", linkedin: "https://www.linkedin.com/in/Bubnick.13" },
  { id: "tristan-cayce", name: "Tristan Cayce", major: "Economics", pcClass: "Beta", hometown: "Lewis Center, OH", linkedin: "https://www.linkedin.com/in/cayce.11" },
  { id: "lukas-cengic", name: "Lukas Cengic", major: "Accounting", pcClass: "Alpha", hometown: "Cleveland, OH", linkedin: "https://www.linkedin.com/in/cengic.2" },
  { id: "kai-cheung", name: "Kai Cheung", major: "Accounting", pcClass: "Gamma", hometown: "Dayton, OH", linkedin: "https://www.linkedin.com/in/cheung.297" },
  { id: "peter-conser", name: "Peter Conser", major: "Economics", pcClass: "Alpha", hometown: "Chicago, IL", linkedin: "https://www.linkedin.com/in/Conser.3" },
  { id: "george-di-iaconi", name: "George Di Iaconi", major: "Economics & Real Estate", pcClass: "Gamma", hometown: "Bethesda, MD", linkedin: "https://www.linkedin.com/in/diiaconi.1" },
  { id: "mananya-ellendula", name: "Mananya Ellendula", major: "Pre-Law, Finance & PPE (Politics, Philosophy, Economics)", pcClass: "Alpha", hometown: "Dublin, OH" },
  { id: "madelyn-fedor", name: "Madelyn Fedor", major: "Marketing", pcClass: "Alpha", hometown: "Basking Ridge, NJ", linkedin: "https://www.linkedin.com/in/Fedor.44" },
  { id: "samantha-feldman", name: "Samantha Feldman", major: "Finance", pcClass: "Alpha", hometown: "Fort Lauderdale, FL", linkedin: "https://www.linkedin.com/in/Feldman.323" },
  { id: "jonathan-felix", name: "Jonathan Felix", major: "Hospitality Management", pcClass: "Gamma", hometown: "México City, México", linkedin: "https://www.linkedin.com/in/felixsaucedo.1" },
  { id: "liam-frazier", name: "Liam Frazier", major: "Finance", pcClass: "Beta", hometown: "Aliso Viejo, CA", linkedin: "https://www.linkedin.com/in/frazier.616" },
  { id: "rushil-gaddam", name: "Rushil Gaddam", major: "Computer Science & Engineering", pcClass: "Gamma", hometown: "Lewis Center, OH", linkedin: "https://www.linkedin.com/in/gaddam.35" },
  { id: "danny-genek", name: "Danny Genek", major: "Finance", pcClass: "Beta", hometown: "East Windsor, NJ", linkedin: "https://www.linkedin.com/in/Genek.4" },
  { id: "sophie-goldstein", name: "Sophie Goldstein", major: "Undeclared", pcClass: "Gamma", hometown: "Columbus, OH" },
  { id: "emma-groves", name: "Emma Groves", major: "Marketing", pcClass: "Alpha", hometown: "Columbus, OH", linkedin: "https://www.linkedin.com/in/Groves.282" },
  { id: "lilly-gruber", name: "Lilly Gruber", major: "Finance", pcClass: "Alpha", hometown: "Avon Lake, OH", linkedin: "https://www.linkedin.com/in/Gruber.236" },
  { id: "ty-harter", name: "Ty Harter", major: "Undeclared", pcClass: "Alpha", hometown: "Columbus, OH" },
  { id: "madison-heathcote", name: "Madison Heathcote", major: "Industrial & Systems Engineering", pcClass: "Alpha", hometown: "Cleveland, Ohio", linkedin: "https://www.linkedin.com/in/Heathcote.5" },
  { id: "ashlyn-hoffman", name: "Ashlyn Hoffman", major: "Finance", pcClass: "Gamma", hometown: "Cincinnati, OH", linkedin: "https://www.linkedin.com/in/Hoffman.1543" },
  { id: "sasha-homsy", name: "Sasha Homsy", major: "Operations Management", pcClass: "Gamma", hometown: "Dublin, OH", linkedin: "https://www.linkedin.com/in/homsy.7" },
  { id: "gabi-ivler", name: "Gabi Ivler", major: "Finance", pcClass: "Beta", hometown: "Northern Jersey", linkedin: "https://www.linkedin.com/in/Ivler.4" },
  { id: "sahana-karthik", name: "Sahana Karthik", major: "Marketing and Public Policy Analysis (Pre-Law)", pcClass: "Gamma", hometown: "Boston, MA", linkedin: "https://www.linkedin.com/in/karthik.35" },
  { id: "rishika-katakam", name: "Rishika Katakam", major: "Finance", pcClass: "Alpha", hometown: "Chicago, IL", linkedin: "https://www.linkedin.com/in/katakam.5" },
  { id: "gautam-ketkar", name: "Gautam Ketkar", major: "Finance", pcClass: "Beta", hometown: "Norristown, PA", linkedin: "https://www.linkedin.com/in/Ketkar.15" },
  { id: "josh-khodosh", name: "Josh Khodosh", major: "Finance", pcClass: "Beta", hometown: "Cliffside Park,NJ", linkedin: "https://www.linkedin.com/in/Khodosh.1" },
  { id: "kris-kimmel", name: "Kris Kimmel", major: "Accounting & Finance", pcClass: "Beta", hometown: "Cleveland, OH", linkedin: "https://www.linkedin.com/in/Kimmel.136" },
  { id: "sam-klosterman", name: "Sam Klosterman", major: "Undeclared", pcClass: "Alpha", hometown: "Columbus, OH" },
  { id: "ayaan-kokate", name: "Ayaan Kokate", major: "Finance", pcClass: "Gamma", hometown: "Princeton, NJ", linkedin: "https://www.linkedin.com/in/kokate.4" },
  { id: "caden-kozak", name: "Caden Kozak", major: "Finance", pcClass: "Gamma", hometown: "Cleveland, OH", linkedin: "https://www.linkedin.com/in/Kozak.102" },
  { id: "victoria-krulig", name: "Victoria Krulig", major: "Strat. Comm.", pcClass: "Beta", hometown: "Miami, FL", linkedin: "https://www.linkedin.com/in/Krulig.2" },
  { id: "jack-langhurst", name: "Jack Langhurst", major: "Accounting", pcClass: "Alpha", hometown: "Columbus, OH", linkedin: "https://www.linkedin.com/in/langhurst.8" },
  { id: "kevin-li", name: "Kevin Li", major: "Finance & Econ", pcClass: "Alpha", hometown: "Boston, MA", linkedin: "https://www.linkedin.com/in/li.13552" },
  { id: "george-limperis", name: "George Limperis", major: "Finance", pcClass: "Beta", hometown: "Chicago, IL", linkedin: "https://www.linkedin.com/in/Limperis.2" },
  { id: "blake-lloyd", name: "Blake Lloyd", major: "Finance", pcClass: "Beta", hometown: "Baltimore, MD", linkedin: "https://www.linkedin.com/in/Lloyd.530" },
  { id: "nik-mahajan", name: "Nik Mahajan", major: "Finance", pcClass: "Alpha", hometown: "Cleveland, OH", linkedin: "https://www.linkedin.com/in/mahajan.185" },
  { id: "michael-mani", name: "Michael Mani", major: "Finance", pcClass: "Gamma", hometown: "Glenview, IL", linkedin: "https://www.linkedin.com/in/Mani.64" },
  { id: "trista-may", name: "Trista May", major: "Finance", pcClass: "Beta", hometown: "Berlin, CT", linkedin: "https://www.linkedin.com/in/may.819" },
  { id: "rishabh-mehta", name: "Rishabh Mehta", major: "Finance", pcClass: "Beta", hometown: "Cleveland, OH", linkedin: "https://www.linkedin.com/in/Mehta.590" },
  { id: "isaac-merz", name: "Isaac Merz", major: "Operations Management", pcClass: "Beta", hometown: "Naperville, IL", linkedin: "https://www.linkedin.com/in/Merz.101" },
  { id: "joey-mitsch", name: "Joey Mitsch", major: "Finance", pcClass: "Beta", hometown: "Cincinnati, OH", linkedin: "https://www.linkedin.com/in/mitsch.16" },
  { id: "max-moses", name: "Max Moses", major: "Health Sciences", pcClass: "Alpha", hometown: "Cleveland, OH", linkedin: "https://www.linkedin.com/in/Moses.243" },
  { id: "chase-o-brien", name: "Chase O'Brien", major: "Undeclared", pcClass: "Alpha", hometown: "Columbus, OH" },
  { id: "kachi-onyia", name: "Kachi Onyia", major: "Marketing", pcClass: "Alpha", hometown: "Albuquerque, NM", linkedin: "https://www.linkedin.com/in/Onyia.7" },
  { id: "mateo-pattani", name: "Mateo Pattani", major: "Finance", pcClass: "Gamma", hometown: "Marin, CA", linkedin: "https://www.linkedin.com/in/pattani.6" },
  { id: "aashish-prabakaran", name: "Aashish Prabakaran", major: "Finance / Economics", pcClass: "Alpha", hometown: "Columbus, OH", linkedin: "https://www.linkedin.com/in/Prabakaran.8" },
  { id: "max-prunty", name: "Max Prunty", major: "Finance & Real Estate and Urban Analysis", pcClass: "Beta", hometown: "Tappan, NY", linkedin: "https://www.linkedin.com/in/Prunty.26" },
  { id: "jonathan-rawlings", name: "Jonathan Rawlings", major: "Finance", pcClass: "Gamma", hometown: "Columbus, OH", linkedin: "https://www.linkedin.com/in/rawlings.61" },
  { id: "ella-robinson", name: "Ella Robinson", major: "Industrial and Systems Engineering", pcClass: "Alpha", hometown: "Cleveland, OH", linkedin: "https://www.linkedin.com/in/Robinson.3102" },
  { id: "christine-rocco", name: "Christine Rocco", major: "Finance", pcClass: "Alpha", hometown: "Cleveland, OH", linkedin: "https://www.linkedin.com/in/Rocco.77" },
  { id: "jenna-ruether", name: "Jenna Ruether", major: "Acounting", pcClass: "Alpha", hometown: "Akron, OH", linkedin: "https://www.linkedin.com/in/ruether.2" },
  { id: "joelle-sabbat", name: "Joelle Sabbat", major: "Marketing", pcClass: "Alpha", hometown: "Silver Spring, MD", linkedin: "https://www.linkedin.com/in/sabbat.1" },
  { id: "thomas-schwartz", name: "Thomas Schwartz", major: "Accounting", pcClass: "Beta", hometown: "Boston, MA", linkedin: "https://www.linkedin.com/in/schwartz.2390" },
  { id: "tanush-shankar", name: "Tanush Shankar", major: "Finance & Operations Management", pcClass: "Gamma", hometown: "Lewis Center, OH", linkedin: "https://www.linkedin.com/in/shankar.139" },
  { id: "ryan-shelby", name: "Ryan Shelby", major: "Accounting", pcClass: "Alpha", hometown: "Park Ridge, IL", linkedin: "https://www.linkedin.com/in/Shelby.74" },
  { id: "sana-shine", name: "Sana Shine", major: "Operations Management", pcClass: "Alpha", hometown: "Dallas, TX", linkedin: "https://www.linkedin.com/in/Shine.73" },
  { id: "shreya-singh", name: "Shreya Singh", major: "Accounting", pcClass: "Beta", hometown: "Oklahoma City, OK", linkedin: "https://www.linkedin.com/in/Singh.2479" },
  { id: "charlie-slate", name: "Charlie Slate", major: "Marketing", pcClass: "Gamma", hometown: "Boston, MA", linkedin: "https://www.linkedin.com/in/Slate.45" },
  { id: "natalie-slezak", name: "Natalie Slezak", major: "Accounting", pcClass: "Beta", hometown: "North East, MD", linkedin: "https://www.linkedin.com/in/Slezak.34" },
  { id: "connor-smith", name: "Connor Smith", major: "Finance", pcClass: "Gamma", hometown: "Cleveland, OH", linkedin: "https://www.linkedin.com/in/Smith.16854" },
  { id: "anna-snyder", name: "Anna Snyder", major: "Finance", pcClass: "Beta", hometown: "Pittsburgh, PA", linkedin: "https://www.linkedin.com/in/Snyder.2187" },
  { id: "colin-southworth", name: "Colin Southworth", major: "Finance & Accounting", pcClass: "Beta", hometown: "Cleveland, OH", linkedin: "https://www.linkedin.com/in/Southworth.44" },
  { id: "carter-spera", name: "Carter Spera", major: "Economics", pcClass: "Gamma", hometown: "Fairfax, VA", linkedin: "https://www.linkedin.com/in/Spera.15" },
  { id: "samara-stein", name: "Samara Stein", major: "Logistics & Operations", pcClass: "Alpha", hometown: "New Jersey", linkedin: "https://www.linkedin.com/in/stein.635" },
  { id: "shagoon-subudhi", name: "Shagoon Subudhi", major: "Finance", pcClass: "Alpha", hometown: "Fremont, CA", linkedin: "https://www.linkedin.com/in/subudhi.3" },
  { id: "aleksandar-sudar", name: "Aleksandar Sudar", major: "Marketing", pcClass: "Gamma", hometown: "Tallmadge, OH", linkedin: "https://www.linkedin.com/in/sudar.6" },
  { id: "matthew-thompson", name: "Matthew Thompson", major: "Construction Systems Management", pcClass: "Gamma", hometown: "Brewster, NY", linkedin: "https://www.linkedin.com/in/thompson.4726" },
  { id: "tisha-vasudeva", name: "Tisha Vasudeva", major: "Finance and Info Systems", pcClass: "Alpha", hometown: "Chicago, IL", linkedin: "https://www.linkedin.com/in/vasudeva.10" },
  { id: "danny-vavas", name: "Danny Vavas", major: "Finance", pcClass: "Gamma", hometown: "Brooklyn, NY", linkedin: "https://www.linkedin.com/in/Vavas.1" },
  { id: "shritha-velaga", name: "Shritha Velaga", major: "Neuroscience and Economics", pcClass: "Gamma", hometown: "Princeton, NJ", linkedin: "https://www.linkedin.com/in/Velaga.5" },
  { id: "alyssa-wickes", name: "Alyssa Wickes", major: "Marketing", pcClass: "Beta", hometown: "Columbus, OH", linkedin: "https://www.linkedin.com/in/Wickes.12" },
  { id: "jino-yoon", name: "Jino Yoon", major: "Finance (Pre-Law)", pcClass: "Gamma", hometown: "Anaheim, CA", linkedin: "https://www.linkedin.com/in/yoon.752" },
  { id: "austyn-yunger", name: "Austyn Yunger", major: "Finance", pcClass: "Alpha", hometown: "Dayton, OH", linkedin: "https://www.linkedin.com/in/yunger.5" },
];

export const FILTERS = {
  pcClasses: ["Freshman", "Sophomore", "Junior", "Senior"] as const,
  roles: [
    "President", "VP of Operations", "VP of Membership", "VP of Finance",
    "VP of Brotherhood", "VP of Professional Dev", "VP of Service", "Secretary",
  ] as const,
};
